spring:
  application:
    name: DuoBloom

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 50
      maximum-pool-size: 10
      idle-timeout: 60000
      connection-timeout: 10000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Seoul
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  session:
    store-type: redis
    timeout: 1800s

  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        secure: true
        http-only: true
      timeout: 60m

cloud:
  aws:
    s3:
      bucket: duobloom-bucket
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}

db:
  thread-count: 16
  connections-per-task: 2
